<script src="https://giscus.app/client.js"
        data-repo="sergioSHKLR/doutrina.org"
        data-repo-id="R_kgDOJLbJUg"
        data-category="General"
        data-category-id="DIC_kwDOJLbJUs4CZYXa"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="pt"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>